In [1]:
#check numpy version
import numpy as np
print(np.__version__)


2.3.0


In [4]:
lst = ([1,2,"3",4,5])
arr = np.array(lst)
arr

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [58]:
arr = np.array([1,2,3,4,5],ndmin=6)
arr

array([[[[[[1, 2, 3, 4, 5]]]]]])

In [5]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [10]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr3 = np.ones(5)
arr3


array([1., 1., 1., 1., 1.])

In [3]:
arr4 = np.zeros(5)
arr4

array([0., 0., 0., 0., 0.])

In [ ]:
#creating 2D array
arr4 = np.zeros([2,3])
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr5 = np.linspace(1,10,50)
arr5

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
#2D array
arr6 = np.arange(1,31).reshape(5,6)
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr7 = np.random.randint(1,100,10)
arr7

array([ 6, 22, 92, 18, 65, 65, 28, 93, 45,  4], dtype=int32)

In [ ]:
#arr7 = np.random.randint(1,100,10)
arr7 = np.random.random(10)
arr7

array([0.98222415, 0.18792965, 0.7096136 , 0.22203147, 0.12614646,
       0.23970514, 0.41552009, 0.95498984, 0.51933956, 0.46755065])

In [18]:
arr8 = np.arange(1,61).reshape(5,12)
arr8

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [19]:
arr8 = np.arange(60).reshape(5,12)
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [20]:
arr8 = np.arange(60).reshape(5,12)
print(arr8.shape)
print(arr8.dtype)
print(arr8.size)
print(arr8.ndim)

(5, 12)
int64
60
2


### Multidimentional array convert 1D

In [25]:
arr8.ravel()
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [23]:
arr8 = np.arange(60).reshape(5,12)
print(arr8.shape)
arr9 = arr8.T.shape
arr9

(5, 12)


(12, 5)

### Indexing and Slicing (1D)


In [ ]:
#Indexing
arr8 = np.arange(60).reshape(5,12)
print(arr8,"\n")
print(arr8[1,7])



[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59]] 

19


In [37]:
#Slicing
arr8 = np.arange(60).reshape(5,12)
print(arr8,"\n")
print(arr8[1:4,3:6])

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59]] 

[[15 16 17]
 [27 28 29]
 [39 40 41]]


In [52]:
arr8 = np.arange(60).reshape(12,5)
print(arr8,"\n")
print(arr8[1:3,8:11])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]] 

[]


In [39]:
arr8[::-1]

array([[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [40]:
arr8[::-1,::-1]

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48],
       [47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36],
       [35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

### 3D Array

In [43]:
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [46]:
arr7 = np.random.randint(1,100,size=(3,5,5))
arr7


array([[[66, 69, 41, 30, 17],
        [59,  1, 80, 57, 97],
        [66, 65, 95, 77, 90],
        [99, 93, 46, 28, 48],
        [44, 32, 40, 38, 88]],

       [[90, 93,  8, 54, 36],
        [47,  9, 45, 44, 80],
        [78, 41,  5, 94, 62],
        [69, 11, 36, 84, 98],
        [33, 91, 68, 80, 44]],

       [[51, 97, 27, 15, 55],
        [96, 40, 91, 15, 11],
        [61, 43, 95,  5, 69],
        [65, 91, 36, 35, 80],
        [95, 49, 24, 34, 13]]], dtype=int32)

### Slicing in 3D array

In [ ]:
#slicing in 3d array 
#syntax -
# [table start : table end : tables skip, row start : row end : row skip, col start : col end : col skip]

In [50]:
arr10[0:,1:4,2:4]

array([[[  7,   8],
        [ 12,  13],
        [ 17,  18]],

       [[ 82,  83],
        [ 87,  88],
        [ 92,  93]],

       [[157, 158],
        [162, 163],
        [167, 168]]])

In [ ]:
#arr8
np.max(arr8)
np.min(arr8) 
np.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr11 = np.array([2,5,1,9])
arr11.argsort()  # it will sort the array in ascending order and return the index of the sorted array
arr11

array([2, 5, 1, 9])

In [55]:
arr11*2

array([ 4, 10,  2, 18])

In [56]:
arr11+2

array([ 4,  7,  3, 11])

In [ ]:
arr12 =